name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Install kubectl
        run: |
          if ! [ -x "$(command -v kubectl)" ]; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin
          fi

      - name: Add /usr/local/bin to PATH
        run: echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV

      - name: Set KUBECONFIG
        run: echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Verify kubectl Installation
        run: kubectl version --client

      - name: Verify kubectl Cluster Access
        run: kubectl get nodes

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/go-server go-server=${{ secrets.DOCKER_USERNAME }}/go-server:latest
