name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Version Tag
        id: vars
        run: |
          # Use the short Git SHA as the version (can be customized)
          VERSION=$(git rev-parse --short HEAD)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          # Build and tag the Docker image with both `latest` and the version tag
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-server:latest -t ${{ secrets.DOCKER_USERNAME }}/go-server:${{ env.VERSION }} .

          # Push both tags to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/go-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/go-server:${{ env.VERSION }}

      - name: Trigger Workflow via HTTP
        run: |
          curl -X GET "https://workflow.brightsideserve.com/trigger?version=${{ env.VERSION }}"
