name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/go-server:latest

      - name: Add /usr/local/bin to PATH
        run: echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV

      - name: Debug PATH and kubectl
        run: |
          echo $PATH
          which kubectl
          kubectl version --client

      - name: Update Kubernetes Deployment
        env:
          KUBECONFIG: /home/pi/kubeconfig.yaml # Update this path to your kubeconfig file
        run: |
          kubectl set image deployment/go-server go-server=${{ secrets.DOCKER_USERNAME }}/go-server:latest
